// src/booksData.js

export const sampleBooks = [
  {
    id: "bk-001",
    title: "Names Brooklyn",
    author: "A. Writer",
    user: "Names Brooklyn",
    coverUrl: "", // put an image URL to see covers
    tags: ["Sci-Fi", "Young Adult", "Drama"],
    rating: "4.5",
    likes: 423,
    bookmarks: 76,
    currentChapter: 0,
    totalChapters: 17,
    dedication: "For my parents, who taught me to read the stars."
  },
  {
    id: "bk-002",
    title: "The Grey Harbor",
    author: "M. Clarke",
    user: "GreyHarborFan",
    coverUrl: "",
    tags: ["Mystery", "Thriller"],
    rating: "4.2",
    likes: 210,
    bookmarks: 45,
    currentChapter: 3,
    totalChapters: 22,
    dedication: "For my parents, who taught me to read the stars."
  },
  {
    id: "bk-003",
    title: "Falling Orbit",
    author: "R. Patel",
    user: "OrbitLover",
    coverUrl: "",
    tags: ["Sci-Fi", "Romance"],
    rating: "4.7",
    likes: 780,
    bookmarks: 132,
    currentChapter: 6,
    totalChapters: 28,
    dedication: "For my parents, who taught me to read the stars."
  },
  {
    id: "bk-004",
    title: "Paper Moons",
    author: "Z. Kim",
    user: "MoonWalker",
    coverUrl: "",
    tags: ["Literary", "Drama"],
    rating: "4.1",
    likes: 155,
    bookmarks: 31,
    currentChapter: 2,
    totalChapters: 12,
    dedication: "For my parents, who taught me to read the stars."
  },
  {
    id: "bk-005",
    title: "Ivory Tower",
    author: "S. Ahmed",
    user: "TowerClimber",
    coverUrl: "",
    tags: ["Fantasy"],
    rating: "4.6",
    likes: 540,
    bookmarks: 90,
    currentChapter: 1,
    totalChapters: 10,
    dedication: "For my parents, who taught me to read the stars."
  },
  {
    id: "bk-006",
    title: "Neon Silence",
    author: "K. Ito",
    user: "NeonCity",
    coverUrl: "",
    tags: ["Cyberpunk"],
    rating: "4.3",
    likes: 320,
    bookmarks: 60,
    currentChapter: 5,
    totalChapters: 24,
    dedication: "For my parents, who taught me to read the stars."
  },
  {
    id: "bk-007",
    title: "Salt & Smoke",
    author: "D. Cruz",
    user: "SaltyReader",
    coverUrl: "",
    tags: ["Adventure"],
    rating: "4.0",
    likes: 120,
    bookmarks: 18,
    currentChapter: 0,
    totalChapters: 8,
    dedication: "For my parents, who taught me to read the stars."
  },
];
